class Middleware:
    async def before_ack(self, broker, message):
        ...

    async def after_ack(self, broker, message):
        ...

    async def before_nack(self, broker, message):
        ...

    async def after_nack(self, broker, message):
        ...

    async def before_consumer_start(self, broker, consumer):
        ...

    async def after_consumer_start(self, broker, consumer):
        ...

    async def before_publish(self, broker, topic, message):
        ...

    async def after_publish(self, broker, topic, message):
        ...

    async def after_skip_message(self, broker, message):
        ...

    async def before_process_message(self, broker, message):
        ...

    async def after_process_message(self, broker, message, exc=None):
        ...

    async def before_service_start(self, broker):
        ...

    async def after_service_start(self, broker):
        ...

    async def before_service_shutdown(self, broker):
        ...

    async def after_service_shutdown(self, broker):
        ...
