site_name: "Aio Services"
site_description: aio_services, Event driven microservice framework for Python
theme:
  name: "material"
  palette:
  - scheme: default
    primary: cyan
    accent: teal
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: slate
    primary: cyan
    accent: teal
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
repo_name: RaRhAeu/aio-services
repo_url: https://github.com/RaRhAeu/aio-services
edit_uri: ''
nav:
  - "Aio Services": index.md
  - "Installation": installation.md
  - "Features": features.md
  - "Usage": usage.md
  - "Service": service.md
  - "Backends": backends.md
  - "Consumers": consumers.md
  - "Middlewares": middlewares.md
  - "HTTP": http.md
  - "AsyncAPI": async_api.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            docstring_style: sphinx
